### PR TITLE
listen on port before joining key

### PR DESCRIPTION
**Pull request by joehand**

### CODE REVIEW

**Comment by juliangruber** [comment]
can you describe this change? i'm curious what's happening here

**Comment by mafintosh** [comment]
yea same. is this needed because of a bug in discovery-swarm?

**Comment by joehand** [comment]
> can you describe this change? i'm curious what's happening here

Sure! This is needed so we could specify a port to listen on.

We weren't doing `swarm.listen()` before. The server was starting with discovery-swarm's check to make sure the [server is listening](https://github.com/mafintosh/discovery-swarm/blob/master/index.js#L115) on `swarm.join()`. But there is no way to specify the port if you rely on the discovery swarm to start the server.

It looks like the `swarm._listening` is set synchronously and the check would happen on the next tick. So we can remove the `on('listening')` (see #24).

>  is this needed because of a bug in discovery-swarm?

I don't think there is a bug. To me, it seemed like a bit of magic hand waiving that `swarm.join()` did `swarm.listen()` for you. But if we are okay with that, then we should document it.

**Comment by mafintosh** [comment]
👍 Thanks for the explaination

**Pull request merged**
